language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-dz-angular' ]; then cd .. && eval "mv $currentfolder generator-dz-angular" && cd generator-dz-angular; fi

